global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'block-subscriber'
    static_configs:
      - targets: ['block-subscriber:8000']
    metrics_path: /metrics
    honor_labels: true
